name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        version: 3.x
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose